version: '2'
services:
    zookeeper:
        container_name: wme-zookeeper
        restart: always
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
        depends_on:
          - kafka
    kafka:
        container_name: wme-kafka
        restart: always
        image: wurstmeister/kafka:1.0.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic-jhipster:1:1"
        ports:
            - 9092:9092
